//! On-device semantic search over the user's Markdown library.
//!
//! Embeddings are generated by a local Ollama embed model (e.g.
//! `nomic-embed-text`) via `POST /api/embed`. The index lives in memory and is
//! persisted to `{data_dir}/md-opener/embed_index.json`, rebuilt incrementally
//! by file mtime. Search is brute-force cosine similarity (fast at personal-
//! library scale) run on a blocking thread so it never stalls the async runtime.
//!
//! Everything degrades gracefully: when Ollama or an embed model is absent,
//! `embed_available` returns `None` and the frontend falls back to keyword
//! search. No data ever leaves the machine.

use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::Mutex;

use reqwest::Client;
use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Tuning constants
// ---------------------------------------------------------------------------

const OLLAMA_URL: &str = "http://localhost:11434";
/// Embed-model name fragments we recognise, in preference order.
const EMBED_MODELS: &[&str] = &[
    "nomic-embed-text",
    "mxbai-embed-large",
    "snowflake-arctic-embed",
    "bge-m3",
    "bge-large",
    "bge-small",
    "all-minilm",
];
const CHUNK_MAX_WORDS: usize = 350;
const MIN_CHUNK_WORDS: usize = 12;
const SNIPPET_CHARS: usize = 320;
const MD_EXTENSIONS: &[&str] = &["md", "markdown", "mdown", "mkd", "mdx"];

// ---------------------------------------------------------------------------
// Persisted index
// ---------------------------------------------------------------------------

#[derive(Serialize, Deserialize, Clone)]
pub struct ChunkEntry {
    pub path: String,
    pub file_name: String,
    pub text: String,
    pub embedding: Vec<f32>,
}

#[derive(Serialize, Deserialize, Default)]
pub struct EmbedIndex {
    /// Which embed model built this index (used to invalidate on model change).
    pub model: Option<String>,
    pub chunks: Vec<ChunkEntry>,
    /// path -> mtime_ms at the time it was embedded.
    pub file_mtimes: HashMap<String, u64>,
    pub last_indexed_ms: u64,
}

#[derive(Default)]
pub struct EmbedState {
    pub index: Mutex<EmbedIndex>,
    pub loaded: Mutex<bool>,
    /// True while a (re)index is running — guards against overlapping runs.
    pub indexing: Mutex<bool>,
}

// ---------------------------------------------------------------------------
// Command payloads
// ---------------------------------------------------------------------------

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct IndexResult {
    pub indexed: usize,
    pub skipped: usize,
    pub removed: usize,
    pub total: usize,
    pub busy: bool,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct SemanticMatch {
    pub path: String,
    pub file_name: String,
    pub snippet: String,
    pub score: f32,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct EmbedStatusPayload {
    pub available: bool,
    pub model: Option<String>,
    pub chunk_count: usize,
    pub file_count: usize,
    pub last_indexed_ms: u64,
}

// ---------------------------------------------------------------------------
// Persistence
// ---------------------------------------------------------------------------

fn index_path() -> Option<PathBuf> {
    let dir = dirs::data_dir()?.join("md-opener");
    let _ = std::fs::create_dir_all(&dir);
    Some(dir.join("embed_index.json"))
}

fn ensure_loaded(state: &EmbedState) {
    // Release the `loaded` lock before taking the `index` lock to avoid any
    // lock-ordering hazard.
    {
        let mut loaded = state.loaded.lock().unwrap();
        if *loaded {
            return;
        }
        *loaded = true;
    }
    if let Some(p) = index_path() {
        if let Ok(raw) = std::fs::read_to_string(&p) {
            match serde_json::from_str::<EmbedIndex>(&raw) {
                Ok(idx) => *state.index.lock().unwrap() = idx,
                // Corrupt index — start empty; it rebuilds on next index call.
                Err(e) => eprintln!("[embed] index parse failed, starting empty: {e}"),
            }
        }
    }
}

/// Write a pre-serialized index JSON to disk (called off the index lock).
fn write_index_json(json: String) {
    if let Some(p) = index_path() {
        let _ = std::fs::write(&p, json);
    }
}

// ---------------------------------------------------------------------------
// Markdown chunking (heading/paragraph aware, no extra crates)
// ---------------------------------------------------------------------------

fn word_count(s: &str) -> usize {
    s.split_whitespace().count()
}

fn chunk_markdown(text: &str) -> Vec<String> {
    let mut chunks: Vec<String> = Vec::new();
    let mut current = String::new();

    let flush = |current: &mut String, chunks: &mut Vec<String>| {
        let trimmed = current.trim();
        if word_count(trimmed) >= MIN_CHUNK_WORDS {
            chunks.push(trimmed.to_string());
        }
        current.clear();
    };

    for line in text.lines() {
        let is_heading = line.trim_start().starts_with('#');
        if is_heading && !current.trim().is_empty() {
            flush(&mut current, &mut chunks);
        }
        current.push_str(line);
        current.push('\n');
        if word_count(&current) >= CHUNK_MAX_WORDS {
            flush(&mut current, &mut chunks);
        }
    }
    flush(&mut current, &mut chunks);
    chunks
}

fn is_markdown(path: &std::path::Path) -> bool {
    path.extension()
        .and_then(|e| e.to_str())
        .map(|e| MD_EXTENSIONS.contains(&e.to_ascii_lowercase().as_str()))
        .unwrap_or(false)
}

fn mtime_ms(path: &std::path::Path) -> u64 {
    std::fs::metadata(path)
        .and_then(|m| m.modified())
        .ok()
        .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

// ---------------------------------------------------------------------------
// Cosine similarity
// ---------------------------------------------------------------------------

fn cosine(a: &[f32], b: &[f32]) -> f32 {
    if a.len() != b.len() || a.is_empty() {
        return 0.0;
    }
    let mut dot = 0.0f32;
    let mut na = 0.0f32;
    let mut nb = 0.0f32;
    for i in 0..a.len() {
        dot += a[i] * b[i];
        na += a[i] * a[i];
        nb += b[i] * b[i];
    }
    if na == 0.0 || nb == 0.0 {
        return 0.0;
    }
    dot / (na.sqrt() * nb.sqrt())
}

// ---------------------------------------------------------------------------
// Ollama embed model detection + embedding requests
// ---------------------------------------------------------------------------

#[derive(Deserialize)]
struct TagModel {
    name: String,
}
#[derive(Deserialize)]
struct TagsResponse {
    models: Vec<TagModel>,
}

async fn detect_embed_model(client: &Client) -> Option<String> {
    let resp = client
        .get(format!("{OLLAMA_URL}/api/tags"))
        .timeout(std::time::Duration::from_millis(800))
        .send()
        .await
        .ok()?;
    if !resp.status().is_success() {
        return None;
    }
    let body: TagsResponse = resp.json().await.ok()?;
    for frag in EMBED_MODELS {
        if let Some(m) = body.models.iter().find(|m| m.name.contains(frag)) {
            return Some(m.name.clone());
        }
    }
    None
}

#[derive(Deserialize)]
struct EmbedBatchResponse {
    embeddings: Vec<Vec<f32>>,
}
#[derive(Deserialize)]
struct EmbedSingleResponse {
    embedding: Vec<f32>,
}

/// Embed `inputs` via `/api/embed` (batch), falling back to the older
/// `/api/embeddings` (one request per input) on a 404 for pre-0.3 Ollama.
async fn fetch_embeddings(
    client: &Client,
    model: &str,
    inputs: &[String],
) -> Result<Vec<Vec<f32>>, String> {
    let resp = client
        .post(format!("{OLLAMA_URL}/api/embed"))
        .json(&serde_json::json!({ "model": model, "input": inputs }))
        .send()
        .await
        .map_err(|e| format!("embed request failed: {e}"))?;

    if resp.status().as_u16() == 404 {
        // Legacy endpoint — embed one at a time.
        let mut out = Vec::with_capacity(inputs.len());
        for input in inputs {
            let r = client
                .post(format!("{OLLAMA_URL}/api/embeddings"))
                .json(&serde_json::json!({ "model": model, "prompt": input }))
                .send()
                .await
                .map_err(|e| format!("legacy embed failed: {e}"))?;
            let body: EmbedSingleResponse = r
                .json()
                .await
                .map_err(|e| format!("legacy embed decode failed: {e}"))?;
            out.push(body.embedding);
        }
        return Ok(out);
    }

    if !resp.status().is_success() {
        return Err(format!("embed http {}", resp.status()));
    }
    let body: EmbedBatchResponse = resp
        .json()
        .await
        .map_err(|e| format!("embed decode failed: {e}"))?;
    Ok(body.embeddings)
}

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

/// Embed-model name if Ollama is up and an embed model is installed, else None.
#[tauri::command]
pub async fn embed_available() -> Result<Option<String>, String> {
    let client = Client::new();
    Ok(detect_embed_model(&client).await)
}

/// (Re)index `paths` — only files whose mtime changed are re-embedded; chunks
/// for paths no longer present are dropped. Returns counts for the UI.
#[tauri::command]
pub async fn embed_index(
    paths: Vec<String>,
    prune: bool,
    state: tauri::State<'_, EmbedState>,
) -> Result<IndexResult, String> {
    ensure_loaded(&state);

    // Guard against overlapping runs (e.g. manual reindex + per-file trigger).
    {
        let mut indexing = state.indexing.lock().unwrap();
        if *indexing {
            let total = state.index.lock().unwrap().chunks.len();
            return Ok(IndexResult {
                indexed: 0,
                skipped: 0,
                removed: 0,
                total,
                busy: true,
            });
        }
        *indexing = true;
    }
    // Ensure the busy flag is always cleared, even on early error.
    let result = embed_index_inner(paths, prune, &state).await;
    *state.indexing.lock().unwrap() = false;
    result
}

/// `prune` = true on a FULL-library reindex (drop chunks for files no longer in
/// `paths`). `prune` = false for an INCREMENTAL call (a single/batched file
/// event) — purely additive so it never touches the rest of the index.
async fn embed_index_inner(
    paths: Vec<String>,
    prune: bool,
    state: &EmbedState,
) -> Result<IndexResult, String> {
    let client = Client::new();
    let Some(model) = detect_embed_model(&client).await else {
        let total = state.index.lock().unwrap().chunks.len();
        return Ok(IndexResult {
            indexed: 0,
            skipped: 0,
            removed: 0,
            total,
            busy: false,
        });
    };

    // Snapshot what we need under the lock, then release it for the network I/O.
    let (stale_model, prior_mtimes): (bool, HashMap<String, u64>) = {
        let idx = state.index.lock().unwrap();
        (
            idx.model.as_deref() != Some(model.as_str()),
            idx.file_mtimes.clone(),
        )
    };

    let md_paths: Vec<String> = paths
        .into_iter()
        .filter(|p| is_markdown(std::path::Path::new(p)))
        .collect();

    let mut indexed = 0usize;
    let mut skipped = 0usize;
    let mut fresh_chunks: Vec<ChunkEntry> = Vec::new();
    // Only files we actually (re)embedded this run — drives replacement + mtime.
    let mut new_mtimes: HashMap<String, u64> = HashMap::new();

    for path in &md_paths {
        let p = std::path::Path::new(path);
        let mt = mtime_ms(p);
        // Skip unchanged files (unless the model changed — then re-embed all).
        if !stale_model && prior_mtimes.get(path) == Some(&mt) {
            skipped += 1;
            continue;
        }
        let Ok(content) = std::fs::read_to_string(p) else {
            continue;
        };
        let chunks = chunk_markdown(&content);
        let file_name = p
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or(path)
            .to_string();
        if chunks.is_empty() {
            // Record the mtime so we don't retry, but it contributes no chunks.
            new_mtimes.insert(path.clone(), mt);
            indexed += 1;
            continue;
        }
        match fetch_embeddings(&client, &model, &chunks).await {
            Ok(vecs) => {
                if vecs.len() != chunks.len() {
                    eprintln!(
                        "[embed] {path}: expected {} vectors, got {}",
                        chunks.len(),
                        vecs.len()
                    );
                }
                for (text, embedding) in chunks.into_iter().zip(vecs) {
                    fresh_chunks.push(ChunkEntry {
                        path: path.clone(),
                        file_name: file_name.clone(),
                        text,
                        embedding,
                    });
                }
                new_mtimes.insert(path.clone(), mt);
                indexed += 1;
            }
            // A single file failing must NOT discard the whole run's work.
            Err(e) => eprintln!("[embed] skipping {path}: {e}"),
        }
    }

    // Merge under the lock; serialize while held, write to disk after releasing.
    let keep: std::collections::HashSet<String> = md_paths.iter().cloned().collect();
    let reembedded: std::collections::HashSet<String> =
        new_mtimes.keys().cloned().collect();

    let json = {
        let mut idx = state.index.lock().unwrap();
        if stale_model {
            idx.chunks.clear();
            idx.file_mtimes.clear();
        }
        // Replace chunks for the files we just re-embedded.
        idx.chunks.retain(|c| !reembedded.contains(&c.path));
        let mut removed = 0usize;
        if prune {
            // Full reindex: also drop files no longer present in the library.
            let gone: Vec<String> = idx
                .file_mtimes
                .keys()
                .filter(|p| !keep.contains(*p) && !reembedded.contains(*p))
                .cloned()
                .collect();
            removed = gone.len();
            idx.chunks.retain(|c| keep.contains(&c.path));
            idx.file_mtimes.retain(|p, _| keep.contains(p));
        }
        idx.chunks.extend(fresh_chunks);
        for (p, mt) in new_mtimes {
            idx.file_mtimes.insert(p, mt);
        }
        idx.model = Some(model);
        idx.last_indexed_ms = mtime_now();
        let total = idx.chunks.len();
        let json = serde_json::to_string(&*idx).ok();
        // Stash counts to return after the lock is dropped.
        (json, IndexResult {
            indexed,
            skipped,
            removed,
            total,
            busy: false,
        })
    };
    let (json, result) = json;
    if let Some(j) = json {
        write_index_json(j);
    }
    Ok(result)
}

fn mtime_now() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

/// Semantic search: embed `query`, return top-k chunks by cosine similarity.
/// Returns an empty vec (not an error) when no index / embed model exists.
#[tauri::command]
pub async fn embed_search(
    query: String,
    k: Option<usize>,
    state: tauri::State<'_, EmbedState>,
) -> Result<Vec<SemanticMatch>, String> {
    ensure_loaded(&state);
    let top_k = k.unwrap_or(8).clamp(1, 32);

    let has_chunks = !state.index.lock().unwrap().chunks.is_empty();
    if !has_chunks || query.trim().is_empty() {
        return Ok(Vec::new());
    }

    let client = Client::new();
    let Some(model) = detect_embed_model(&client).await else {
        return Ok(Vec::new());
    };
    let qvecs = fetch_embeddings(&client, &model, &[query]).await?;
    let Some(qvec) = qvecs.into_iter().next() else {
        return Ok(Vec::new());
    };

    // Clone the chunks out and score on a blocking thread (CPU-bound).
    let chunks: Vec<ChunkEntry> = state.index.lock().unwrap().chunks.clone();
    let matches = tauri::async_runtime::spawn_blocking(move || {
        let mut scored: Vec<SemanticMatch> = chunks
            .iter()
            .map(|c| {
                let mut snippet = c.text.clone();
                if snippet.chars().count() > SNIPPET_CHARS {
                    snippet = snippet.chars().take(SNIPPET_CHARS).collect::<String>() + "…";
                }
                SemanticMatch {
                    path: c.path.clone(),
                    file_name: c.file_name.clone(),
                    snippet,
                    score: cosine(&qvec, &c.embedding),
                }
            })
            .collect();
        scored.sort_by(|a, b| b.score.partial_cmp(&a.score).unwrap_or(std::cmp::Ordering::Equal));
        scored.truncate(top_k);
        scored
    })
    .await
    .map_err(|e| format!("scoring failed: {e}"))?;

    Ok(matches)
}

/// Status for the Settings panel.
#[tauri::command]
pub async fn embed_status(
    state: tauri::State<'_, EmbedState>,
) -> Result<EmbedStatusPayload, String> {
    ensure_loaded(&state);
    let client = Client::new();
    let model = detect_embed_model(&client).await;
    let idx = state.index.lock().unwrap();
    let file_count = idx.file_mtimes.len();
    Ok(EmbedStatusPayload {
        available: model.is_some(),
        model,
        chunk_count: idx.chunks.len(),
        file_count,
        last_indexed_ms: idx.last_indexed_ms,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cosine_identical_is_one() {
        let v = vec![0.1, 0.2, 0.3];
        assert!((cosine(&v, &v) - 1.0).abs() < 1e-5);
    }

    #[test]
    fn cosine_orthogonal_is_zero() {
        assert!(cosine(&[1.0, 0.0], &[0.0, 1.0]).abs() < 1e-6);
    }

    #[test]
    fn cosine_dim_mismatch_is_zero() {
        assert_eq!(cosine(&[1.0, 2.0], &[1.0]), 0.0);
    }

    #[test]
    fn chunk_splits_on_headings_and_drops_tiny() {
        let md = "# Title\n\nThis is a reasonably long first paragraph with enough words to count as a real chunk of prose for the test.\n\n## Section\n\nAnother sufficiently long paragraph here that also clears the minimum word threshold for chunking nicely.\n";
        let chunks = chunk_markdown(md);
        assert!(chunks.len() >= 2);
        assert!(chunks[0].starts_with("# Title"));
    }

    #[test]
    fn chunk_drops_empty() {
        assert!(chunk_markdown("# Just a heading\n").is_empty());
    }
}
